DELETE FROM Comments;
DELETE FROM Categories;
DELETE FROM Posts;
DELETE FROM PostCategories;
DELETE FROM Users;

DBCC CHECKIDENT ('[Users]', RESEED, 0);
DBCC CHECKIDENT ('[Posts]', RESEED, 0);
DBCC CHECKIDENT ('[Comments]', RESEED, 0);
DBCC CHECKIDENT ('[Categories]', RESEED, 0);